# Generated by Django 4.1.7 on 2023-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=500, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.CharField(max_length=1000),
        ),
    ]
